INSERT INTO VIDEO_CODEC VALUES ('MPEG2');
INSERT INTO VIDEO_CODEC VALUES ('MPEG4');
INSERT INTO VIDEO_CODEC VALUES ('DivX');
INSERT INTO VIDEO_CODEC VALUES ('H264');

INSERT INTO AUDIO_CODEC VALUES('MP3');
INSERT INTO AUDIO_CODEC VALUES('ACC');
INSERT INTO AUDIO_CODEC VALUES('AC3');

INSERT INTO TEXT_CODEC VALUES ('AQTitle');
INSERT INTO TEXT_CODEC VALUES ('DKS');
INSERT INTO TEXT_CODEC VALUES ('Kate');

COMMIT;